[package]
name = "structs_playground"
version = "0.1.0"
authors = ["David Bailey <davidbailey00@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
